### ISSUE TITLE
[Feature] String constant from external file

### ISSUE THREAD

**Issue by bhagenbourger** [soma-smart/Fakelake#45]
This provider enables to load a list of strings from external data file. Each line of this external file is considered as a value. A value is randomly assigned for each line.  
The parameter **path** contains the path to the file. If file doesn't exist, a error is raised.  

```yaml
- name: external_data
  provider: Constant.external
  path: path/to/data.txt
```
